### ISSUE TITLE
Improve upload file form

### ISSUE THREAD

**Issue by jacobsims** [jacobsims/DwarfBotHTTP#6]
Styling, wording

**Comment by quorth0n** [comment]
I'd be happy to help with this, but what exactly is wrong with its current state? It's minimalistic (& to the point), has clear instructions, and is currently JS-free (a big plus imo). I think it would be easy enough for anyone to pick up right off the bat.

**Comment by jacobsims** [comment]
Ernie did not get this at first

> Oh, I see what happens. You need to click “Upload file"
> Maybe a different wording would work better?
> Like “Start conversion”?

Also, it's not a huge deal, but the tap target is a bit small for touch devices.

**Comment by quorth0n** [comment]
I'll see what I can do.
